### ISSUE TITLE
Clarify the component definition between k8s, odo

### ISSUE THREAD

**Issue by cmoulliard** [gorkem/app-labels#2]
**Issue**

The `Component` definition suggested within your project is different from what k8s proposes [1] and what `odo` uses.

**Definitions**

Gorkem : A component is a set of kubernetes resources, for hosting code or data, that needs to be running in order for the overall software system to work. Each component is a separately deployable and runnable unit. (e.g. frontend, backend, database, integration, queue, ...)

K8s : The component within the architecture (e.g. database, server,...)

odo : a component can be thought of as a microservice. Multiple components will make up an application. A component will have different attributes like storage, etc. Multiple component types are currently supported, like nodejs, perl, php, python, ruby, etc.

**Suggestion**

I propose that we clarify the definition by adopting either the odo vs k8s, Gorkem definition that we add also more examples as defined within the next **Component List**. 

Remark : As a component represents a part of an application, an element, then it will help the architect of an application to provide metadata info about what is the purpose of the module, microservice to be deployed.

**Component Type list**
- Job : application deployed as k8s job and configured using Cron scheduler
- Frontend : a runtime exposing a Web application to the client
- Backend : a runtime which is running, managing the business logic of an application)
- Service : refers to a service installed from a Service Catalog, Helm Chart, OpenShift Template AND could also express if this a database, broker, api gateway, sso, cache, ...
- Integration : application designed using a mediation and routing framework such as Apache Camel, CXF
- Processing : that corresponds to an application which relies on BxMS technology such as Drools = Rules engine, jBPM : Business Processing engine

WDYT: @gorkem, @tkral, @Steve, @Siamak ?

[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Comment by gorkem** [comment]
Is k8s definition and the definition on this document really that different? k8s definition lacks clarity and one of the goals with this document is to be as clear as possible hence I clarified that it is not a single kubernetes resource and it is a unit that can run/deploy on its own. 

odo's definition of a component differs because it makes a distinction between a component that you use (service) and a component that you build and use. Obviously this distinction is important to odo but I am not sure if this is significant for labeling. Even if we make that distinction on the document would we really label a service different from a component?

**Comment by cmoulliard** [comment]
> Is k8s definition and the definition on this document really that different?

Not really to be honest ;-)

**Comment by cmoulliard** [comment]
> Even if we make that distinction on the document would we really label a service different from a component?

As I mentioned in my list, a service is specific component's type. So, it should not labelled differently

**Comment by gorkem** [comment]
@cmoulliard Is there anything we need to do for this one? I am closing it, please reopen if I am missing something.
