### ISSUE TITLE
component label does not match what component means on other tools (e.g. odo)

### ISSUE THREAD

**Issue by jorgemoralespou** [gorkem/app-labels#4]
Adopting this proposal with tools like odo would really be messy as it has already adopted the term "component" to mean the part of the application you're working on, so what you call name, even if they align with what has been proposed by some people at kubernetes.
Like some other times, they've pushed that proposal without much pushback basically because most of the people involved in kubernetes development didn't care. It's fundamentally wrong call this component and not something like role. Even the examples there makes not much sense. :-(

Sadly, we might be late to change that, but will definitely complicate things like `odo`. Also, as these are implemented as labels, a user will see on `components` that have been built with odo, labels (that display on the console), showing something totally different under the key component.

**Comment by gorkem** [comment]
@jorgemoralespou I am not sure I grok this one. My assumption is both 'odo' and 'console' will adopt this recommendation. Do you see a problem with their ability to adopt. 

I am not too much worried about odo's current interpretation as odo is an early stage tool. The important thing is to decide and adopt on the label recommendations so that all our tools can speak the same language.

**Comment by jorgemoralespou** [comment]
@gorkem what I mean is that we will add a label with the `component` in the key that will not match the meaning of component odo has, and that as this is implemented as a label rather than an annotation, a user might potentially see it in the web ui and be totally confused.

**Comment by gorkem** [comment]
Closing this as odo is aligned now.

**Comment by kadel** [comment]
I think that this should be reopened.

It was done just for one demo, but it was not merged.

see https://github.com/openshift/odo/issues/599
