### ISSUE TITLE
Instances and names good practice

### ISSUE THREAD

**Issue by jotak** [gorkem/app-labels#8]
> It is a good practice to check if combination of app.kubernetes.io/part-of, app.kubernetes.io/instance, app.kubernetes.io/name labels lead to a meaningful identifier without repeating parts. For instance coolstore.catalog.mongodb. A repeated part is usually an indicator of a label that can be avoided.

This is somehow contradicting what I can read in kubernetes doc: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#applications-and-instances-of-applications

> The name of an application and the instance name are recorded separately. For example, WordPress has a app.kubernetes.io/name of wordpress while it has an instance name, represented as app.kubernetes.io/instance with a value of wordpress-abcxzy. This enables the application and instance of the application to be identifiable. Every instance of an application must have a unique name.

I tend to prefer what is said in Kubernetes. Have the "instance" label being unique and sufficient to identify something, without having to correlate with "name".

**Comment by gorkem** [comment]
Why do you prefer the instance being unique?

**Comment by jotak** [comment]
For a subjective answer, very specific to my developer case working with istio/kiali : we have metrics stored by "app" and we can identify what an "app" is from one and only one label. That's currently how it works, maybe we'll have to change that. So if the app is identified by `app.kubernetes.io/name` then it's fine, but if the user wants to identify it via `app.kubernetes.io/instance` then it would have to be unique to make it work well with istio/kiali.

And for a more general answer it also seems to me that querying by labels would be facilitated if the instance is unique, instead having to always correlate with app. Basically "instance" alone would never mean anything, one would always have to correlate with app to make any sense of it.

But I'm also probably missing some use cases, what's the pros of avoiding repeating parts?

**Comment by sspeiche** [comment]
+1 to having the recommendation that `instance` be unique. This is causing a problem with how `odo` is structured and gets complicated to have "same name components". I'd say we align with kubernetes recommendation and expand out from there if we find there is a problem with it.
